export const authActionTypes = {
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    PHONE_VALIDATION_INITIALIZED: 'PHONE_VALIDATION_INITIALIZED',
    LOG_OUT: 'LOG_OUT',
}
